### ISSUE TITLE
Is True

### ISSUE THREAD

**Issue by shrink** [pr-mpt/assertions#20]
`is-equal` can be used to do this but it requires an exact match (case-sensitive) so `is-boolean` can include all YAMLish version of true / false.

Maybe break down into `is-boolean-equal` which accepts "true" or "false" and then `is-boolean-true` and `is-boolean-false` can be shortcuts to that.

```yaml
assertion: npm://@assertions/is-boolean-true
expected: "true"
actual: ${{ steps.boolean.outputs.result }}
```

- [ ] Update [`actions-assert`'s integration tests](https://github.com/pr-mpt/actions-assert/blob/main/.github/workflows/tests-integration.yml) to use this instead
