### ISSUE TITLE
Is Empty

### ISSUE THREAD

**Issue by shrink** [pr-mpt/assertions#22]

**Comment by shrink** [comment]
The same functionality would work for testing whether or not a Secret is available in the Environment, i.e:

```yaml
      - name: Test for presence of Terraform Cloud Credentials
        uses: pr-mpt/actions-assert@v3
        id: has-credentials
        with:
          assertion: local://.github/has-secret
          actual: "${{ secrets.TERRAFORM_CLOUD_CREDENTIALS }}"
          error-on-fail: false
      - name: Apply Configuration to Workspace (if Environment has Terraform Cloud Credentials)
        if: steps.has-credentials.outputs.passed == 'true'
        uses: dflook/terraform-apply@v1
        with:
          workspace: "${{ needs.workspace.outputs.id }}"
          auto_approve: true
          variables: |
            environments = [${{ needs.environments.outputs.list }}]
```

```javascript
module.exports = function (_, actual) {
  return {
    pass: pass = (actual !== null),
    message: pass ? "Secret value found" : "No secret value found"
  }
}
```

So it might be worth publishing this as both `is-empty` and `has-secret` -- where `has-secret` is effectively just an alias.
